name: Deploy Bot to VPS

on:
  push:
    branches:
      - deploy  # Change this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: |
          ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VPS
      env:
        HOST: ${{ secrets.VPS_HOST }}
        USER: ${{ secrets.VPS_USER }}
        BOT_PATH: ${{ secrets.BOT_PATH }}
      run: |
        ssh -o StrictHostKeyChecking=no $USER@$HOST "
          cd $BOT_PATH && \
          git pull origin main && \
          docker compose down && docker compose -f compose.yml -f compose.prod.yml up --build -d
        "
